apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  generateName: "game-server-"
spec:
  ports:
  - name: default
    portPolicy: Dynamic
    containerPort: 7777
  template:
    spec:
      containers:
      - name: game-server
        image: jausseran/agoneserver:1.8
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "500m"