apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  generateName: "game-server-"
spec:
  ports:
  - name: default
    portPolicy: Dynamic
    containerPort: 7777
  template:
    spec:
      containers:
      - name: game-server
        image: jausseran/agoneserver:1.11
        resources:
          requests:
            memory: "32Mi"
            cpu: "5m"
          limits:
            memory: "32Mi"
            cpu: "5m"